name: transaccion
description: A new Flutter project.


publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"



dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  splashscreen: ^1.3.5
  moor: ^4.5.0
  sqflite: ^2.0.2+1
  path_provider: ^2.0.9
  socket_io_client: ^2.0.0-beta.2
  flutter_search_bar: ^2.1.0
  mysql1: ^0.19.2
  fluttertoast: ^8.0.8
  loader_search_bar: 1.0.3+3
  loading_overlay: ^0.3.0
  vibration: ^1.7.3
  flutter_rounded_date_picker: 2.0.2
  datetime_picker_formfield: 2.0.0
  shared_preferences: ^2.0.15
  intl: 0.17.0
  

  carousel_slider: ^4.1.1
  curved_navigation_bar: ^1.0.3
  image_picker: 0.8.5+3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.1

flutter_icons:
  image_path: "assets/images/icon.png"
  android: true
  ios: true


  flutter_lints: ^1.0.0


flutter:

  uses-material-design: true


  assets:
    - assets/
    - assets/images/

